@host = https://graph-monad.kindynos.mx/api
# @host = http://localhost:4200/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2MjQsImFkZHJlc3MiOiIweEE4ZUExNTAzODkyNjE4OGU3YmQ0NDY2ZDNlYjRiM2MxMTM4NjY0NDUiLCJpYXQiOjE3NTY5NzI5MDAsImV4cCI6MTc1NzE0NTcwMCwiaXNzIjoiUGF5YVNheXNUaGVXb3JkIn0.2ljI06YTN8VplI8Ncy49H86iRV5cwuAFTogwpgSlRr4
### get profile
GET {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

### get app stats
GET {{host}}/stats
Content-Type: application/json

### get user ranking
GET {{host}}/user/4426/financials
Content-Type: application/json

### get leaderboard
GET {{host}}/point?take=10&skip=10&sortBy=referrals
Content-Type: application/json

### get point history
GET {{host}}/point/history?take=10
Content-Type: application/json

### patch profile
PATCH {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "test",
    "email": "Teste@g.com"
}

### get nonce
GET {{host}}/auth/nonce?address=0x9860e2b4079452C41f86AEC5Da0F5C8b43b42363
Content-Type: application/json

### web3 login
POST {{host}}/auth/login
Content-Type: application/json

{

    "address": "0x9860e2b4079452C41f86AEC5Da0F5C8b43b42363",
    "signature": "0x9860e2b4079452C41f86AEC5Da0F5C8b43b42363",
    "message": "Welcome to Tayadex!\n\nClick to sign in and accept the Tayadex Terms of Service.\n\nThis request will not trigger a blockchain transaction or cost any gas fees.\n\nWallet: 0x9860e2b4079452C41f86AEC5Da0F5C8b43b42363\nNonce: 0ek0teawhu1m8f5svzty8ai\nTimestamp: 2025-09-02T23:40:43.805Z"

}